import { useState, useMemo } from 'react';
import clsx from 'clsx';
import styled, { keyframes } from 'styled-components';
import { Space, Button, Row, Col, Tooltip } from 'antd';
import {
  ListChevronsDownUp,
  ListChevronsUpDown,
  RefreshCw,
} from 'lucide-react';
import LoadingOutlined from '@ant-design/icons/LoadingOutlined';
import EllipsisWrapper from '@/components/EllipsisWrapper';
import { makeIterable } from '@/utils/iteration';
import { GroupedQuestion } from '@/hooks/useRecommendedQuestionsInstruction';

const CategorySectionBlock = styled.div`
  // background: var(--gray-1);
  // border: 1px solid var(--gray-4);
  // border-radius: 12px;
  // padding: 16px;
`;

const QuestionBlock = styled.div`
  background: var(--gray-1);
  user-select: none;
  height: 150px;
  transition: border-color ease 0.2s;

  &:hover:not(.is-disabled) {
    border-color: var(--rust-orange-6) !important;
  }

  &.is-active {
    border-color: var(--rust-orange-6) !important;
  }

  &.is-disabled {
    opacity: 0.8;
  }
`;

const MAX_EXPANDED_QUESTIONS = 9;
// Default render slot count when there's no prior data — match the
// 3x3 grid so the loading state visually matches what's about to appear.
const SKELETON_COUNT = 9;

const shimmer = keyframes`
  0% { background-position: 200% 0; }
  100% { background-position: -200% 0; }
`;

const SkeletonBlock = styled.div`
  height: 150px;
  border-radius: 16px;
  background: linear-gradient(
    90deg,
    var(--gray-3) 0%,
    var(--gray-2) 50%,
    var(--gray-3) 100%
  );
  background-size: 200% 100%;
  animation: ${shimmer} 1.4s linear infinite;
`;

interface Props {
  onSelect: (payload: { sql: string; question: string }) => void;
  recommendedQuestions: GroupedQuestion[];
  loading: boolean;
  /** When true, replaces the grid with skeleton placeholders while a
   *  fresh batch of questions is being generated by the LLM. */
  regenerating?: boolean;
  /** Optional callback fired when the user clicks the refresh icon
   *  in the header. If omitted the icon is hidden (e.g. when the
   *  parent doesn't support regeneration). */
  onRegenerate?: () => void;
}

const QuestionTemplate = ({
  category,
  sql,
  question,
  onSelect,
  loading,
  selectedQuestion,
}) => {
  const isSelected = selectedQuestion === question;
  const isDisabled = loading && !isSelected;

  const onClick = () => {
    if (loading) return;
    onSelect({ sql, question });
  };

  return (
    <Col span={8}>
      <QuestionBlock
        className={clsx(
          'border border-gray-5 rounded-2xl px-3 pt-3 pb-4',
          loading ? 'cursor-wait' : 'cursor-pointer',
          {
            'is-active': isSelected,
            'is-disabled cursor-not-allowed': isDisabled,
          },
        )}
        onClick={onClick}
      >
        <div className="d-flex justify-space-between align-center text-sm mb-3">
          <div
            className="bg-gray-3 px-2 rounded-pill text-truncate text-medium"
            title={category}
          >
            {category}
          </div>
          {isSelected && loading && <LoadingOutlined className="ml-1 gray-7" />}
        </div>
        <EllipsisWrapper multipleLine={4} text={question} />
      </QuestionBlock>
    </Col>
  );
};

const QuestionColumnIterator = makeIterable(QuestionTemplate);

export default function RecommendedQuestionsPrompt(props: Props) {
  const {
    onSelect,
    recommendedQuestions,
    loading,
    regenerating = false,
    onRegenerate,
  } = props;

  const [isExpanded, setIsExpanded] = useState<boolean>(false);
  const [selectedQuestion, setSelectedQuestion] = useState<string>('');

  const questionList = useMemo(() => {
    return recommendedQuestions.slice(
      0,
      isExpanded ? undefined : MAX_EXPANDED_QUESTIONS,
    );
  }, [recommendedQuestions, isExpanded]);

  const onHandleToggle = () => setIsExpanded((prev) => !prev);

  const showExpandButton = recommendedQuestions.length > MAX_EXPANDED_QUESTIONS;

  const onSelectQuestion = (payload: { sql: string; question: string }) => {
    onSelect(payload);
    setSelectedQuestion(payload.question);
  };

  return (
    <div className="px-10 py-6">
      <div className="d-flex align-center justify-center" style={{ position: 'relative' }}>
        <h2 className="text-center mb-0">What data would you like to explore?</h2>
        {onRegenerate && (
          <Tooltip title="Regenerate questions">
            <Button
              className="d-flex align-center"
              type="text"
              size="small"
              icon={<RefreshCw size={16} />}
              onClick={onRegenerate}
              loading={regenerating}
              disabled={regenerating || loading}
              style={{ position: 'absolute', right: 0 }}
              aria-label="Regenerate recommended questions"
            />
          </Tooltip>
        )}
      </div>
      <Space
        style={{ width: 680, marginTop: 16 }}
        direction="vertical"
        size={[0, 16]}
      >
        <CategorySectionBlock>
          {regenerating ? (
            <Row gutter={[16, 16]}>
              {Array.from({ length: SKELETON_COUNT }).map((_, i) => (
                <Col span={8} key={i}>
                  <SkeletonBlock />
                </Col>
              ))}
            </Row>
          ) : (
            <Row gutter={[16, 16]}>
              <QuestionColumnIterator
                data={questionList}
                onSelect={onSelectQuestion}
                loading={loading}
                selectedQuestion={selectedQuestion}
              />
            </Row>
          )}
          {!regenerating && showExpandButton && (
            <div className="text-right">
              <Button
                onClick={() => onHandleToggle()}
                className="gray-6 mt-3 d-flex align-center"
                type="text"
                size="small"
                icon={
                  isExpanded ? (
                    <ListChevronsDownUp size={16} />
                  ) : (
                    <ListChevronsUpDown className="mr-1" size={16} />
                  )
                }
              >
                {isExpanded ? 'Show less' : 'Show more'}
              </Button>
            </div>
          )}
        </CategorySectionBlock>
      </Space>
    </div>
  );
}
